// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240228045358_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Amenidad = "",
                            Detalle = "Amplia Villa para pasarla bien",
                            FechaActualizacion = new DateTime(2024, 2, 27, 22, 53, 55, 350, DateTimeKind.Local).AddTicks(9742),
                            FechaCreacion = new DateTime(2024, 2, 27, 22, 53, 55, 350, DateTimeKind.Local).AddTicks(9728),
                            ImagenUrl = "",
                            MetrosCuadrados = 120,
                            Nombre = "Villa deluxe",
                            Ocupantes = 4,
                            Tarifa = 150.0
                        },
                        new
                        {
                            id = 2,
                            Amenidad = "",
                            Detalle = "Amplia Villa con vista al mar",
                            FechaActualizacion = new DateTime(2024, 2, 27, 22, 53, 55, 350, DateTimeKind.Local).AddTicks(9751),
                            FechaCreacion = new DateTime(2024, 2, 27, 22, 53, 55, 350, DateTimeKind.Local).AddTicks(9750),
                            ImagenUrl = "",
                            MetrosCuadrados = 150,
                            Nombre = "Villa premium",
                            Ocupantes = 8,
                            Tarifa = 350.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
